# Generated by Django 3.1.3 on 2020-11-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Showpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('post_name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='images/')),
                ('age', models.IntegerField(default=15)),
                ('address', models.CharField(max_length=50)),
                ('phn', models.CharField(max_length=20)),
                ('experience', models.IntegerField(default=0)),
                ('salary', models.CharField(max_length=10)),
                ('rating', models.IntegerField(default=1)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
    ]
