# Generated by Django 3.1.3 on 2020-11-25 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Electrician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('experience', models.CharField(max_length=20)),
                ('esalary', models.CharField(max_length=20)),
                ('contract', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('votes_total', models.IntegerField(default=1)),
                ('skill', models.CharField(max_length=150)),
                ('url', models.CharField(max_length=50)),
                ('cv', models.ImageField(upload_to='cvs/')),
                ('image', models.ImageField(upload_to='images/')),
                ('pub_date', models.DateTimeField()),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
