# Generated by Django 3.1.3 on 2020-11-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricians', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electrician',
            name='cv',
            field=models.FileField(upload_to='cvs/'),
        ),
    ]
