# Generated by Django 3.1.3 on 2020-11-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricians', '0003_auto_20201126_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electrician',
            name='cv',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
