# Generated by Django 3.1.3 on 2020-11-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricians', '0004_auto_20201126_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electrician',
            name='address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='electrician',
            name='skill',
            field=models.CharField(max_length=150),
        ),
    ]
