# Generated by Django 3.1.3 on 2020-11-25 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electricians', '0005_auto_20201126_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electrician',
            name='cv',
        ),
    ]
