# Generated by Django 3.1.3 on 2020-11-25 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Createjob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=20)),
                ('salary', models.CharField(max_length=20)),
                ('contract', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('votes_total', models.IntegerField(default=1)),
                ('description', models.CharField(max_length=150)),
                ('url', models.CharField(max_length=50)),
                ('icon', models.ImageField(upload_to='images/')),
                ('pub_date', models.DateTimeField()),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
