# Generated by Django 3.1.3 on 2020-11-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createjobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createjob',
            name='address',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='createjob',
            name='contract',
            field=models.CharField(max_length=11),
        ),
    ]
