# Generated by Django 3.1.3 on 2020-11-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createjobs', '0002_auto_20201125_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createjob',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
